# code the pipeline 
name: ML Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ml_pipeline:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python 3.8
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn pytest

      # Step 4: Run Preprocessing
      - name: Run Preprocessing
        run: python preprocessing.py

      # Step 5: Train the model
      - name: Train Model
        run: python train_model.py

      # Step 6: Run tests with pytest
      - name: Run Tests
        run: pytest --maxfail=1 --disable-warnings -q
